apiVersion: apps/v1
kind: Deployment
metadata:
  name: fasten-server-old-format-master
  namespace: fasten
spec:
  selector:
    matchLabels:
      app: fasten-server-old-format-master
  replicas: 2
  template:
    metadata:
      labels:
        app: fasten-server-old-format-master
    spec:
      containers:
        - name: fasten-server-old-format-master
          image: docker.pkg.github.com/fasten-project/fasten/fasten.server.old-format-master:latest
          args: ["-k", "$(KAFKA_ADDR)", "-pl", "MetadataDBExtension", "-kt", "MetadataDBExtension=fasten.opal.cg.3", "-d", "$(PSQL_DB)", "-du", "$(PSQL_USER)", "-b", "/mnt/fasten/repos"]
          ports:
            - containerPort: 3010
          env:
            - name: FASTEN_DBPASS
              valueFrom:
                secretKeyRef:
                  key: psql.pwd
                  name: psql-pwd
            - name: PSQL_DB
              valueFrom:
                configMapKeyRef:
                  key: psql.db.url
                  name: psql.db
            - name: PSQL_USER
              valueFrom:
                configMapKeyRef:
                  key: psql.db.username
                  name: psql.db.user
            - name: KAFKA_ADDR
              valueFrom:
                configMapKeyRef:
                  key: kafka.addr
                  name: kafka         
      nodeSelector:
        monster.node: "true"
      imagePullSecrets:
        - name: fasten.docker.registry
